### ISSUE TITLE
Integração com site de vagas

### ISSUE THREAD

**Issue by alexandrealfa** [DEV-Zone-BR/The-Hammer#1]
- [ ] Construir integração com site de vagas
- [ ] Construir comparador de vagas
- [ ] Construir Timer 
- [ ] Construir notificador (alerta)
- [ ] Construir integração com canal

**Comment by alexandrealfa** [comment]
```
- Construir integração com site de vagas
```
```
- Construir comparador de vagas
```
```
- Construir Timer 
```
```
- Construir notificador (alerta)
```
```
- Construir integração com canal
```

**Comment by LuanComputacao** [comment]
Uma boa opção para pegar push notifications
[Tornado Web](https://www.tornadoweb.org/en/stable/)

**Comment by LuanComputacao** [comment]
[Tornado Websocket](https://www.tornadoweb.org/en/stable/websocket.html)
